### ISSUE TITLE
Server install

### ISSUE THREAD

**Issue by hawk0484** [Bubbus/XCF#49]
We are not quite sure what is going wrong but we have tried both ACF and XCF but neither have worked, we have managed to get the models in and we can easily spawn them in game however the ACF/XCF menu isnt there, to clarify we can spawn in the ACF/XCF models like the engines but we cannot see the ACF/XCF menu.

**Comment by seanterrorx** [comment]
I also have this problem, where the XCF works on single player but when I add it to my server it doesn't appear in the tool menu. I have made sure that it is the newest version and I have also checked the install, ad as OP stated it is just the stool and sent that are no existent not the models

**Comment by Bubbus** [comment]
Hi, XCF isn't supported anymore.  We've been replacing it with addons which plug into the normal ACF, because it takes less effort to keep up-to-date.  Check out https://github.com/Bubbus/acf-missiles, https://github.com/Bubbus/ACF-SWEPs and https://github.com/Bubbus/ACF-Launchers.
