### ISSUE TITLE
Tried to use a NULL physics object!

### ISSUE THREAD

**Issue by Bryantdl7** [Bubbus/XCF#50]
ERROR] addons/xcf/lua/entities/acf_gearbox.lua:427: Tried to use a NULL physics object!
           1. GetMass - [C]:-1
            2. CheckLegal - addons/xcf/lua/entities/acf_gearbox.lua:427
             3. unknown - addons/xcf/lua/entities/acf_gearbox.lua:417

**Comment by Bubbus** [comment]
Hi, XCF isn't supported anymore. We've been replacing it with addons which plug into the normal ACF, because it takes less effort to keep up-to-date. Check out https://github.com/Bubbus/acf-missiles, https://github.com/Bubbus/ACF-SWEPs and https://github.com/Bubbus/ACF-Launchers.
